### ISSUE TITLE
automatically update *all* release versions in concourse-bosh-deployment

### ISSUE THREAD

**Issue by cirocosta** [concourse/ci#273]
### challenge

the process of bumping the versions of `bbr`, `windows_utilities`, and now `uaa`
and `credhub` (see concourse/concourse-bosh-deployment#211) in `versions.yaml`
of any of those releases is entirely manual, requiring one to go through the
[`concourse` pipeline], collect the versions, and then bump.

not only tedious, but also error-prone.

[`concourse` pipeline]: https://ci.concourse-ci.org/teams/main/pipelines/concourse

### what would be better

we already have the process in place to bump the versions of `concourse`, `bpm`,
and `postgres`.

```yaml
---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/unit

inputs:
- name: concourse-bosh-deployment
- name: concourse-boshio
- name: bpm-release
- name: postgres-release

outputs:
- name: bumped-repo

run:
  path: concourse-bosh-deployment/ci/scripts/bump-versions
```

https://github.com/concourse/concourse-bosh-deployment/blob/3b1759a78aa66c95b4ed7c0b16ad1e953b663191/ci/bump-versions.yml

```bash
cat ./concourse-bosh-deployment/versions.yml | \
  sed -e "s/concourse_version: .*/concourse_version: '$concourse_version'/" | \
  sed -e "s/concourse_sha1: .*/concourse_sha1: '$(cat concourse-boshio/sha1)'/" | \
  sed -e "s/bpm_version: .*/bpm_version: '$(cat bpm-release/version)'/" | \
  sed -e "s/bpm_sha1: .*/bpm_sha1: '$(cat bpm-release/sha1)'/" | \
  sed -e "s/postgres_version: .*/postgres_version: '$(cat postgres-release/version)'/" | \
  sed -e "s/postgres_sha1: .*/postgres_sha1: '$(cat postgres-release/sha1)'/" \
  > bumped-repo/versions.yml
```

https://github.com/concourse/concourse-bosh-deployment/blob/3b1759a78aa66c95b4ed7c0b16ad1e953b663191/ci/scripts/bump-versions

we could add to those the releases that are not currently tracked, making the
whole file automatically updated when shipping new versions of concourse.

to do so, we'd need to update the task with more inputs, as well as the job

```yaml

- name: bump-cbd-versions
  serial: true
  plan:
  - in_parallel:
    - get: concourse-boshio
      trigger: true
    - get: unit-image
      passed: [shipit]
    - get: cbd-master
    - get: version
      passed: [shipit]
    - get: bpm-release
      passed: [shipit]
    - get: postgres-release
      passed: [shipit]
    #
    # <<< more releases ...
    #
  - task: bump-versions
    file: cbd-master/ci/bump-versions.yml
    input_mapping: {concourse-bosh-deployment: cbd-master}
    image: unit-image
  - put: cbd-master
    params:
      repository: bumped-repo
      merge: true
```

https://github.com/concourse/ci/blob/9c4e4765e86e82565a36f715c85d2c95a651c9fb/pipelines/concourse.yml#L1320-L1342
